import 'dotenv/config';import express from 'express';import mongoose from 'mongoose';import cors from 'cors';import rateLimit from 'express-rate-limit';import morgan from 'morgan';import jwt from 'jsonwebtoken';import bcrypt from 'bcryptjs';import multer from 'multer';import nodemailer from 'nodemailer';
import {Project,Event,Volunteer,GalleryImage,ContactMessage,SurveyResponse,DonationEnquiry,AdminUser,SearchAnalytics} from './models.js';
const app=express(),port=process.env.PORT||5000,upload=multer({dest:'uploads/',limits:{fileSize:5*1024*1024}});app.set('trust proxy',1);app.use(cors());app.use(express.json({limit:'100kb'}));app.use('/uploads',express.static('uploads'));app.use(morgan('tiny'));app.use('/api',rateLimit({windowMs:15*60*1000,max:200,standardHeaders:true}));
const mailer=process.env.SMTP_HOST?nodemailer.createTransport({host:process.env.SMTP_HOST,port:+process.env.SMTP_PORT||587,auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}):null;const email=async(to,subject,text)=>{if(!mailer||!to)return false;try{await mailer.sendMail({from:process.env.MAIL_FROM||'EarthKind <noreply@earthkind.org>',to,subject,text});return true}catch(e){console.error('Email send failed:',e.message);return false}};
const clean=s=>typeof s==='string'?s.trim().slice(0,1000):s;const publicFields='name description location image category date capacity registered url caption tags skills availability';
async function paginated(Model,req,res,sort){const page=Math.max(1,+req.query.page||1),limit=Math.min(60,Math.max(1,+req.query.limit||20)),filter={};if(req.query.category)filter.category=req.query.category;if(req.query.location)filter.location=new RegExp(req.query.location,'i');const [data,total]=await Promise.all([Model.find(filter).sort(sort).skip((page-1)*limit).limit(limit),Model.countDocuments(filter)]);res.json({data,page,limit,total,pages:Math.ceil(total/limit)})}
app.get('/api/projects',(req,res)=>paginated(Project,req,res,{featured:-1,createdAt:-1}));
app.get('/api/events',(req,res)=>paginated(Event,req,res,{date:1}));
app.get('/api/gallery',(req,res)=>paginated(GalleryImage,req,res,{createdAt:-1}));
app.get('/api/search',async(req,res)=>{const q=clean(req.query.q||'');if(q.length<2)return res.json({query:q,projects:[],events:[],volunteer:[],gallery:[],pages:[]});const regex=new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i');const [projects,events,volunteer,gallery]=await Promise.all([Project.find({$or:[{name:regex},{category:regex},{location:regex},{description:regex}]}).limit(8),Event.find({$or:[{name:regex},{location:regex},{description:regex}]}).limit(8),Volunteer.find({$or:[{skills:regex},{location:regex}]}).select('skills location availability').limit(8),GalleryImage.find({$or:[{tags:regex},{caption:regex},{location:regex}]}).limit(8)]);SearchAnalytics.findOneAndUpdate({query:q.toLowerCase()},{$inc:{count:1},lastSearched:new Date()},{upsert:true}).catch(()=>{});res.json({query:q,projects,events,volunteer:volunteer.map(v=>({name:`Volunteer opportunity: ${v.skills||'Community support'}`,description:v.availability,location:v.location})),gallery:gallery.map(g=>({name:g.caption||'EarthKind gallery moment',description:(g.tags||[]).join(', '),image:g.url})),pages:[{name:'About EarthKind',description:'Our mission, people and history.'},{name:'Donate',description:'Help community ideas take root.'},{name:'Contact',description:'Get in touch with our team.'}]})});
function valid(fields){return(req,res,next)=>{for(const f of fields)if(!clean(req.body[f]))return res.status(400).json({error:`${f} is required`});next()}}
app.post('/api/volunteers',valid(['name','email']),async(req,res)=>{const registration=await Volunteer.create({name:clean(req.body.name),email:clean(req.body.email),skills:clean(req.body.skills),availability:clean(req.body.availability),location:clean(req.body.location)});email(registration.email,'Your ImpactStay registration','Thanks for registering. We will send role details shortly.');res.status(201).json(registration)});
app.post('/api/contact',valid(['email']),async(req,res)=>{const contact=await ContactMessage.create({name:clean(req.body.name),email:clean(req.body.email),message:clean(req.body.message),status:'new',followUpAt:new Date(Date.now()+24*60*60*1000)});const visitorName=clean(req.body.name)||'there';const confirmation=await email(contact.email,'We received your message — EarthKind',`Hi ${visitorName},\n\nThank you for contacting EarthKind. We have received your message and our team will follow up with you shortly.\n\nYour message:\n${contact.message||'No message provided'}\n\nThank you,\nEarthKind Team`);const notification=await email(process.env.ADMIN_EMAIL,'New EarthKind contact enquiry',`New contact enquiry from ${visitorName}\nEmail: ${contact.email}\n\nMessage:\n${contact.message||'No message provided'}\n\nFollow-up is due: ${contact.followUpAt.toISOString()}`);res.status(201).json({success:true,contactId:contact._id,emailSent:confirmation,adminNotified:notification});});
app.post('/api/survey',valid(['name','community']),async(req,res)=>res.status(201).json(await SurveyResponse.create({name:clean(req.body.name),community:clean(req.body.community),priority:clean(req.body.priority),notes:clean(req.body.notes)})));
app.post('/api/donation-enquiries',valid(['name','email']),async(req,res)=>res.status(201).json(await DonationEnquiry.create({name:clean(req.body.name),email:clean(req.body.email),amount:clean(req.body.amount),message:clean(req.body.message)})));
app.post('/api/auth/login',async(req,res)=>{const user=await AdminUser.findOne({email:clean(req.body.email).toLowerCase()});if(!user||!await bcrypt.compare(req.body.password||'',user.passwordHash))return res.status(401).json({error:'Invalid credentials'});res.json({token:jwt.sign({id:user.id,email:user.email},process.env.JWT_SECRET||'dev-secret',{expiresIn:'8h'})})});
function admin(req,res,next){try{req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),process.env.JWT_SECRET||'dev-secret');next()}catch{return res.status(401).json({error:'Admin access required'})}}
const models={projects:Project,events:Event,gallery:GalleryImage,volunteers:Volunteer,contacts:ContactMessage};
app.get('/api/admin/dashboard',admin,async(req,res)=>{const [projects,events,volunteers,gallery,searches]=await Promise.all([Project.countDocuments(),Event.countDocuments(),Volunteer.countDocuments(),GalleryImage.countDocuments(),SearchAnalytics.find().sort({count:-1}).limit(10)]);res.json({projects,events,volunteers,gallery,searches})});
app.get('/api/admin/stats',admin,async(req,res)=>{const [projects,events,volunteers,contacts,donationEnquiries]=await Promise.all([Project.countDocuments(),Event.countDocuments(),Volunteer.countDocuments(),ContactMessage.countDocuments(),DonationEnquiry.countDocuments()]);res.json({projects,events,volunteers,contacts,donationEnquiries})});
app.get('/api/admin/:collection',admin,async(req,res)=>{const M=models[req.params.collection];if(!M)return res.sendStatus(404);res.json(await M.find().sort({createdAt:-1}))});
app.post('/api/admin/:collection',admin,async(req,res)=>{const M=models[req.params.collection];if(!M)return res.sendStatus(404);res.status(201).json(await M.create(req.body))});
app.put('/api/admin/:collection/:id',admin,async(req,res)=>{const M=models[req.params.collection];if(!M)return res.sendStatus(404);res.json(await M.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true}))});
app.delete('/api/admin/:collection/:id',admin,async(req,res)=>{const M=models[req.params.collection];if(!M)return res.sendStatus(404);await M.findByIdAndDelete(req.params.id);res.sendStatus(204)});
app.post('/api/admin/upload',admin,upload.single('image'),(req,res)=>{if(!req.file)return res.status(400).json({error:'Image file is required'});res.status(201).json({url:`/uploads/${req.file.filename}`,filename:req.file.originalname})});
app.get('/api/admin/export/:type',admin,async(req,res)=>{const M={volunteers:Volunteer,contacts:ContactMessage,surveys:SurveyResponse}[req.params.type];if(!M)return res.sendStatus(404);const rows=await M.find().lean();const keys=[...new Set(rows.flatMap(Object.keys))].filter(k=>!['_id','__v'].includes(k));const csv=[keys.join(','),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(','))].join('\n');res.type('text/csv').attachment(`${req.params.type}.csv`).send(csv)});
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Something went wrong'})});mongoose.connect(process.env.MONGODB_URI||'mongodb://127.0.0.1:27017/earthkind').then(()=>app.listen(port,()=>console.log(`EarthKind API on :${port}`))).catch(e=>{console.error('MongoDB connection failed:',e.message);process.exit(1)});
