services:
  - type: web
    name: earthkind-api
    runtime: node
    rootDir: build-a-full-stack-highly-animated/backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: FRONTEND_ORIGIN
        value: https://earthkind-web.onrender.com

staticSites:
  - name: earthkind-web
    rootDir: build-a-full-stack-highly-animated/frontend
    buildCommand: ""
    staticPublishPath: .
