const API='https://ngo-pi3s.onrender.com/api';
const token=()=>localStorage.getItem('earthkind_token');
const $=selector=>document.querySelector(selector);
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const auth=()=>({Authorization:`Bearer ${token()}`});
async function get(path){const response=await fetch(`${API}${path}`,{headers:auth()});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Request failed');return data;}
async function dashboard(){try{const d=await get('/admin/dashboard');$('#login').style.display='none';$('#dashboard').style.display='block';$('#stats').innerHTML=[['Projects',d.projects,'*'],['Events',d.events,'o'],['Volunteers',d.volunteers,'+'],['Contacts',d.contacts||0,'@'],['Gallery moments',d.gallery,'#']].map(x=>`<div class="admin-stat"><span>${x[2]} ${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('#searches').innerHTML=d.searches.length?d.searches.map(s=>`<div class="search-row"><span>"${escapeHtml(s.query)}"</span><b>${s.count} searches</b></div>`).join(''):'<p>No searches logged yet.</p>';}catch(error){localStorage.removeItem('earthkind_token');$('#loginError').textContent=error.message;}}
async function reviewNgo(id,action){const reason=action==='verify'?'':prompt('Reason or review note (optional):','');if(action!=='verify'&&reason===null)return;try{await fetch(`${API}/admin/ngos/${encodeURIComponent(id)}/${action==='request-changes'?'request-changes':action}`,{method:'PUT',headers:{...auth(),'Content-Type':'application/json'},body:JSON.stringify({reason})}).then(async response=>{if(!response.ok)throw new Error((await response.json()).error||'Review action failed');});await loadCollection('ngos');}catch(error){alert(error.message);}}
function renderNgos(items){if(!items.length)return '<p>No NGOs found.</p>';return items.map(ngo=>`<div><span><b>${escapeHtml(ngo.name)}</b><br><small>${escapeHtml(ngo.city||'')} ${escapeHtml(ngo.state||'')} - ${escapeHtml(ngo.status)}</small></span><span>${ngo.status==='PENDING'?'<button data-review="verify" data-id="'+ngo._id+'">Verify</button>':''}${ngo.status!=='SUSPENDED'?'<button class="danger" data-review="suspend" data-id="'+ngo._id+'">Suspend</button>':''}<button data-review="request-changes" data-id="${ngo._id}">Changes</button><button class="danger" data-review="reject" data-id="${ngo._id}">Reject</button></span></div>`).join('');}
async function loadCollection(collection){try{const data=await get(`/admin/${collection}`);if(collection==='ngos'){$('#records').innerHTML=renderNgos(data);$('#records').querySelectorAll('[data-review]').forEach(button=>button.onclick=()=>reviewNgo(button.dataset.id,button.dataset.review));return;}$('#records').innerHTML=data.slice(0,8).map(item=>`<div><span>${escapeHtml(item.name||item.caption||item.email||'Untitled record')}</span><small>${escapeHtml(item.email&&item.name?`${item.email} - ${item.status||'new'}`:(item.location||item.status||''))}</small></div>`).join('')||'No records yet.';}catch(error){$('#records').textContent=error.message;}}
if(token())dashboard();
$('#loginForm').onsubmit=async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button');button.textContent='Checking...';const body=Object.fromEntries(new FormData(event.currentTarget));try{const response=await fetch(`${API}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Login failed');if(data.user?.role!=='ADMIN')throw new Error('Admin account required');localStorage.setItem('earthkind_token',data.token);dashboard();}catch(error){$('#loginError').textContent=error.message;button.textContent='Enter dashboard';}};
document.querySelectorAll('[data-collection]').forEach(button=>button.onclick=()=>loadCollection(button.dataset.collection));
$('#logout').onclick=async()=>{try{await fetch(`${API}/auth/logout`,{method:'POST',headers:auth()});}catch(error){}localStorage.removeItem('earthkind_token');location.reload();};
